name: Test

on:
  push:
    # trigger on main branch
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: "Metadata: Git"
        id: git-meta
        run:
          export TRUNCATED_GITHUB_SHA=$(echo ${{ github.sha }} | cut -c1-7);
          export VERSION=${GITHUB_REF/refs\/tags\//};
          echo "minisha=${TRUNCATED_GITHUB_SHA}" >> $GITHUB_OUTPUT;
          echo "version=${VERSION}" >> $GITHUB_OUTPUT;
          echo "versionlabel=${VERSION}+${TRUNCATED_GITHUB_SHA}" >> $GITHUB_OUTPUT;
      
      - name: "Print Metadata: Git"
        run: echo ${{ steps.git-meta.outputs.minisha }}
    
      - name: "Docker: Build and Push Image"
        id: ghcr-docker
        uses: 'penguin-statistics/actions/ghcr-docker@main'
        with:
          version: ${{ steps.git-meta.outputs.version }}
          repository: 'penguin-statistics/frontend-v2'
          build-args: |
            TRUNCATED_GITHUB_SHA=${{ steps.git-meta.outputs.minisha }}
